### ISSUE TITLE
Creating Tickets

### ISSUE THREAD

**Issue by ryangurn** [DeskPRO/deskpro-api-php#6]
When creating the tickets, is there a way to have it automatically send out an email to the user with the ticket contents. I have created a ticket using the api and when I create it, there is no email that is sent out to the user. Please advise on how I can make this work. 

Thanks,
Ryan Gurnick

**Comment by chroder** [comment]
Hi Ryan,

Emails are sent via triggers, not by any kind of special API parameter. See here:

https://www.deskpro.com/manuals/admin-manual/admin-manual.html#ticket-triggers

Since this isn't really related to the API, I recommend submitting a ticket to support@deskpro.com if you find yourself needing a bit of help with configuring triggers.

**Comment by ryangurn** [comment]
Thanks

On Wed, Jan 7, 2015 at 10:26 AM, Christopher Nadeau <
notifications@github.com> wrote:

> Closed #6 <https://github.com/DeskPRO/deskpro-api-php/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DeskPRO/deskpro-api-php/issues/6#event-215449932>.
>



-- 
Thanks,
Ryan Gurnick
(818) 835-3177
ryangurnick@gmail.com
